FROM docker.io/python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir psycopg2-binary && \
    pip install --no-cache-dir \
        "dbt-core==1.8.7" \
        "dbt-postgres==1.8.2"

CMD ["dbt", "run"]

