services:
  destination_postgres:
    build:
      context: ./init
    ports:
      - "5434:5432"
    networks:
      - elt_network
    environment:
      POSTGRES_DB: ${DEST_DB_NAME}
      POSTGRES_USER: ${DEST_DB_USER}
      POSTGRES_PASSWORD: ${DEST_DB_PASSWORD}
    volumes:
      - dest_pg_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DEST_DB_USER} -d ${DEST_DB_NAME} || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 20

  postgres:
    image: docker.io/library/postgres:17
    networks:
      - elt_network
    environment:
      POSTGRES_USER: ${AIRFLOW_DB_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_DB_PASSWORD}
      POSTGRES_DB: ${AIRFLOW_DB_NAME}
    volumes:
      - airflow_db_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${AIRFLOW_DB_USER} -d ${AIRFLOW_DB_NAME} || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 20

  init-airflow:
    image: docker.io/apache/airflow:2.9.3
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - elt_network
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
    command: bash -c "airflow db init && airflow users create --username airflow --password password --firstname John --lastname Doe --role Admin --email admin@example.com"

  webserver:
    build:
      context: ./airflow
    user: root
    depends_on:
      postgres:
        condition: service_healthy
      init-airflow:
        condition: service_completed_successfully
    networks:
      - elt_network
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags:z
      - ./elt:/opt/airflow/elt:z
      - ./dbt:/opt/dbt:z
      - ~/.dbt:/root/.dbt:z
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
      AIRFLOW__CORE__EXECUTOR: ${AIRFLOW__CORE__EXECUTOR}
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY}
      LOAD_EX: ${LOAD_EX}
      ALPHAVANTAGE_API_KEY: ${ALPHAVANTAGE_API_KEY}
      DEST_DB_HOST: ${DEST_DB_HOST}
      DEST_DB_PORT: ${DEST_DB_PORT}
      DEST_DB_NAME: ${DEST_DB_NAME}
      DEST_DB_USER: ${DEST_DB_USER}
      DEST_DB_PASSWORD: ${DEST_DB_PASSWORD}
    command: webserver
    restart: unless-stopped

  scheduler:
    build:
      context: ./airflow
    user: root
    depends_on:
      postgres:
        condition: service_healthy
      init-airflow:
        condition: service_completed_successfully
    networks:
      - elt_network
    volumes:
      - ./airflow/dags:/opt/airflow/dags:z
      - ./elt:/opt/airflow/elt:z
      - ./dbt:/opt/dbt:z
      - ~/.dbt:/root/.dbt:z
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
      AIRFLOW__CORE__EXECUTOR: ${AIRFLOW__CORE__EXECUTOR}
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY}
      LOAD_EX: ${LOAD_EX}
      ALPHAVANTAGE_API_KEY: ${ALPHAVANTAGE_API_KEY}
      DEST_DB_HOST: ${DEST_DB_HOST}
      DEST_DB_PORT: ${DEST_DB_PORT}
      DEST_DB_NAME: ${DEST_DB_NAME}
      DEST_DB_USER: ${DEST_DB_USER}
      DEST_DB_PASSWORD: ${DEST_DB_PASSWORD}
    command: scheduler
    restart: unless-stopped

networks:
  elt_network:
    driver: bridge

volumes:
  airflow_db_data:
  dest_pg_data:
