FROM docker.io/apache/airflow:2.9.3

USER root

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends gnupg ca-certificates curl lsb-release; \
    echo "deb [signed-by=/usr/share/keyrings/postgresql.gpg] http://apt.postgresql.org/pub/repos/apt $(. /etc/os-release && echo $VERSION_CODENAME)-pgdg main" > /etc/apt/sources.list.d/pgdg.list; \
    curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o /usr/share/keyrings/postgresql.gpg; \
    apt-get update; \
    apt-get install -y --no-install-recommends postgresql-client-17; \
    rm -rf /var/lib/apt/lists/*;

USER airflow
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir \
        "dbt-core==1.8.7" \
        "dbt-postgres==1.8.2"

USER root
RUN ln -sf /home/airflow/.local/bin/dbt /usr/local/bin/dbt

USER airflow

